# numpyで配列を作成する

In [1]:
import numpy as np

## 基本的な作成方法
1. 要素を直接指定して配列を作成する（np.array）
2. 要素がゼロの配列を作成する（np.zeros）
3. 要素が1の配列を作成する（np.ones）
4. 要素が空の配列を作成する（np.empty）
5. 要素を一意の数値に指定して作成する（np.full）
6. 順列要素として作成する（np.arange）

### 1. 要素を直接指定して配列を作成する（np.array）

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# 配列の情報を取得する
print('array: ', a)
print('a.shape: ', a.shape)
print('a.size: ', a.size)
print('a.sum: ', a.sum())

# 関数化
def info(array):
    print('array: ', array)
    print('shape: ', array.shape)
    print('size: ', array.size)
    print('sum: ', array.sum())

array:  [[1 2 3]
 [4 5 6]]
a.shape:  (2, 3)
a.size:  6
a.sum:  21


### 2. 要素がゼロの配列を作成する（np.zeros）

In [3]:
a = np.zeros(4)
info(a)

array:  [0. 0. 0. 0.]
shape:  (4,)
size:  4
sum:  0.0


### 3. 要素が1の配列を作成する（np.ones）

In [4]:
a = np.ones(4)
info(a)

array:  [1. 1. 1. 1.]
shape:  (4,)
size:  4
sum:  4.0


### 4. 要素が空の配列を作成する（np.empty）

In [9]:
a = np.empty(shape=[4])
info(a)

array:  [0. 0. 0. 0.]
shape:  (4,)
size:  4
sum:  0.0


### 5. 要素を一意の数値に指定して作成する（np.full）

In [13]:
a = np.full([5, 4], 10)
info(a)

array:  [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
shape:  (5, 4)
size:  20
sum:  200


### 6. 順列要素として作成する（np.arange）

In [14]:
a = np.arange(10)
info(a)

array:  [0 1 2 3 4 5 6 7 8 9]
shape:  (10,)
size:  10
sum:  45


In [17]:
# stopで指定した数字は入らないので注意
a = np.arange(start=10, stop=20, step=2)
info(a)

array:  [10 12 14 16 18]
shape:  (5,)
size:  5
sum:  70
